[project]
name = "odoo-addons-oca-partner-contact"
version = "17.0.20250604.1"
dependencies = [
    "odoo-addon-account_partner_company_group>=17.0dev,<17.1dev",
    "odoo-addon-base_country_state_translatable>=17.0dev,<17.1dev",
    "odoo-addon-base_location>=17.0dev,<17.1dev",
    "odoo-addon-base_location_geonames_import>=17.0dev,<17.1dev",
    "odoo-addon-base_location_nuts>=17.0dev,<17.1dev",
    "odoo-addon-base_partner_company_group>=17.0dev,<17.1dev",
    "odoo-addon-base_partner_sequence>=17.0dev,<17.1dev",
    "odoo-addon-crm_partner_company_group>=17.0dev,<17.1dev",
    "odoo-addon-partner_address_split>=17.0dev,<17.1dev",
    "odoo-addon-partner_address_street3>=17.0dev,<17.1dev",
    "odoo-addon-partner_affiliate>=17.0dev,<17.1dev",
    "odoo-addon-partner_category_security>=17.0dev,<17.1dev",
    "odoo-addon-partner_category_type>=17.0dev,<17.1dev",
    "odoo-addon-partner_company_default>=17.0dev,<17.1dev",
    "odoo-addon-partner_company_group>=17.0dev,<17.1dev",
    "odoo-addon-partner_company_type>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_access_link>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_address_default>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_birthdate>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_birthplace>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_department>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_gender>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_job_position>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_lang>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_nationality>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_personal_information_page>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_role>=17.0dev,<17.1dev",
    "odoo-addon-partner_country_lang>=17.0dev,<17.1dev",
    "odoo-addon-partner_deduplicate_acl>=17.0dev,<17.1dev",
    "odoo-addon-partner_deduplicate_by_website>=17.0dev,<17.1dev",
    "odoo-addon-partner_deduplicate_filter>=17.0dev,<17.1dev",
    "odoo-addon-partner_disable_gravatar>=17.0dev,<17.1dev",
    "odoo-addon-partner_display_name_line_break>=17.0dev,<17.1dev",
    "odoo-addon-partner_duns>=17.0dev,<17.1dev",
    "odoo-addon-partner_email_check>=17.0dev,<17.1dev",
    "odoo-addon-partner_email_duplicate_warn>=17.0dev,<17.1dev",
    "odoo-addon-partner_employee_quantity>=17.0dev,<17.1dev",
    "odoo-addon-partner_external_map>=17.0dev,<17.1dev",
    "odoo-addon-partner_fax>=17.0dev,<17.1dev",
    "odoo-addon-partner_firstname>=17.0dev,<17.1dev",
    "odoo-addon-partner_identification>=17.0dev,<17.1dev",
    "odoo-addon-partner_identification_gln>=17.0dev,<17.1dev",
    "odoo-addon-partner_industry_secondary>=17.0dev,<17.1dev",
    "odoo-addon-partner_manual_rank>=17.0dev,<17.1dev",
    "odoo-addon-partner_multi_relation>=17.0dev,<17.1dev",
    "odoo-addon-partner_pricelist_search>=17.0dev,<17.1dev",
    "odoo-addon-partner_priority>=17.0dev,<17.1dev",
    "odoo-addon-partner_property>=17.0dev,<17.1dev",
    "odoo-addon-partner_readonly_security>=17.0dev,<17.1dev",
    "odoo-addon-partner_ref_unique>=17.0dev,<17.1dev",
    "odoo-addon-partner_second_lastname>=17.0dev,<17.1dev",
    "odoo-addon-partner_stage>=17.0dev,<17.1dev",
    "odoo-addon-partner_stage_only_confirmed>=17.0dev,<17.1dev",
    "odoo-addon-partner_tier_validation>=17.0dev,<17.1dev",
    "odoo-addon-partner_title_active>=17.0dev,<17.1dev",
    "odoo-addon-partner_tz>=17.0dev,<17.1dev",
    "odoo-addon-partner_utm_source>=17.0dev,<17.1dev",
    "odoo-addon-partner_vat_unique>=17.0dev,<17.1dev",
    "odoo-addon-sale_partner_company_group>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
